/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * An enumeration.
 */
export enum LiqorsOverPeriodOptions {
  _1Week = <any>'1WEEK',
  _1Month = <any>'1MONTH',
  _6Months = <any>'6MONTHS',
}
