/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class OpenBookTrade {
  'signature': string;
  'blockDatetime': string;
  'market': string;
  'openOrders': string;
  'bid': boolean;
  'maker': boolean;
  'referrerRebate'?: number;
  'orderId': string;
  'clientOrderId'?: string;
  'feeTier': number;
  'instructionNum': number;
  'size': number;
  'price': number;
  'side': string;
  'feeCost': number;
  'openOrdersOwner': string;
  'baseSymbol'?: string;
  'quoteSymbol'?: string;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'signature',
      baseName: 'signature',
      type: 'string',
    },
    {
      name: 'blockDatetime',
      baseName: 'block_datetime',
      type: 'string',
    },
    {
      name: 'market',
      baseName: 'market',
      type: 'string',
    },
    {
      name: 'openOrders',
      baseName: 'open_orders',
      type: 'string',
    },
    {
      name: 'bid',
      baseName: 'bid',
      type: 'boolean',
    },
    {
      name: 'maker',
      baseName: 'maker',
      type: 'boolean',
    },
    {
      name: 'referrerRebate',
      baseName: 'referrer_rebate',
      type: 'number',
    },
    {
      name: 'orderId',
      baseName: 'order_id',
      type: 'string',
    },
    {
      name: 'clientOrderId',
      baseName: 'client_order_id',
      type: 'string',
    },
    {
      name: 'feeTier',
      baseName: 'fee_tier',
      type: 'number',
    },
    {
      name: 'instructionNum',
      baseName: 'instruction_num',
      type: 'number',
    },
    {
      name: 'size',
      baseName: 'size',
      type: 'number',
    },
    {
      name: 'price',
      baseName: 'price',
      type: 'number',
    },
    {
      name: 'side',
      baseName: 'side',
      type: 'string',
    },
    {
      name: 'feeCost',
      baseName: 'fee_cost',
      type: 'number',
    },
    {
      name: 'openOrdersOwner',
      baseName: 'open_orders_owner',
      type: 'string',
    },
    {
      name: 'baseSymbol',
      baseName: 'base_symbol',
      type: 'string',
    },
    {
      name: 'quoteSymbol',
      baseName: 'quote_symbol',
      type: 'string',
    },
  ];

  static getAttributeTypeMap() {
    return OpenBookTrade.attributeTypeMap;
  }
}
