/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
 * An enumeration.
 */
export enum Resolution {
  _1 = <any>'1',
  _3 = <any>'3',
  _5 = <any>'5',
  _15 = <any>'15',
  _30 = <any>'30',
  _45 = <any>'45',
  _60 = <any>'60',
  _120 = <any>'120',
  _180 = <any>'180',
  _240 = <any>'240',
  _1440 = <any>'1440',
}
