/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UserSettingsUnsigned {
  'walletPk': string;
  'accountTourSeen': boolean;
  'swapTourSeen': boolean;
  'tradeTourSeen': boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'walletPk',
      baseName: 'wallet_pk',
      type: 'string',
    },
    {
      name: 'accountTourSeen',
      baseName: 'account_tour_seen',
      type: 'boolean',
    },
    {
      name: 'swapTourSeen',
      baseName: 'swap_tour_seen',
      type: 'boolean',
    },
    {
      name: 'tradeTourSeen',
      baseName: 'trade_tour_seen',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return UserSettingsUnsigned.attributeTypeMap;
  }
}
